
import { Project } from './types';

export const projects: Project[] = [
  {
    title: 'Mermaid Online',
    description: 'Online visual builder for Mermaid diagrams with pan & zoom functionality—create flowcharts and more effortlessly.',
    language: 'TypeScript',
    liveUrl: 'https://mermaid-online.vercel.app/',
    liveButtonText: 'Build Live',
    githubUrl: 'https://github.com/JuanchoGithub/online-diagram',
  },
  {
    title: 'Truco AI',
    description: 'AI-powered single-player Truco card game with bluffing and unpredictability. Classic Argentine game!',
    language: 'TypeScript',
    liveUrl: 'https://trucai.vercel.app/',
    liveButtonText: 'Play Live',
    githubUrl: 'https://github.com/JuanchoGithub/truco-ai',
  },
  {
    title: 'Solitaire Collection',
    description: 'A collection of classic solitaire games with smooth animations and responsive design.',
    language: 'TypeScript',
    liveUrl: 'https://lonely-cards.vercel.app/',
    liveButtonText: 'Play Live',
    githubUrl: 'https://github.com/JuanchoGithub/solitaire-collection',
  },
  {
    title: 'Lecturalia',
    description: 'Interactive reading app for kids in 3rd grade and up, with engaging stories and questions.',
    language: 'TypeScript',
    liveUrl: 'https://lecturalia.vercel.app/',
    liveButtonText: 'Explore Live',
    githubUrl: 'https://github.com/JuanchoGithub/lecturalia',
  },
  {
    title: 'Super Vibe Trek',
    description: 'Browser-based turn-based Star Trek game: explore the galaxy, manage crew, and handle diplomacy/combat.',
    language: 'TypeScript',
    liveUrl: 'https://super-vibe-trek.vercel.app/',
    liveButtonText: 'Explore Live',
    githubUrl: 'https://github.com/JuanchoGithub/Star-Trek-Exploration',
  },
  {
    title: 'Head Tracking 3D Test',
    description: 'Experimental 3D head tracking demo with infinity mirror effects and grid visuals.',
    language: 'TypeScript',
    liveUrl: 'https://head-tracking-3d-test.vercel.app/',
    liveButtonText: 'View Live',
    githubUrl: 'https://github.com/JuanchoGithub/head-tracking-3d-test',
  },
  {
    title: 'Kirby Jump',
    description: 'Vibe-coded Kirby obstacle course inspired by Roblox and Mario Maker levels—built with my son!',
    language: 'TypeScript',
    liveUrl: 'https://kirby-jump-nine.vercel.app/',
    liveButtonText: 'Play Live',
    githubUrl: 'https://github.com/JuanchoGithub/Kirby-Jump-',
  },
  {
    title: 'PNG URL to SVG',
    description: 'Simple tool to convert PNG images from URLs to SVGs, now with background removal.',
    language: 'TypeScript',
    liveUrl: 'https://png-url-to-svg.vercel.app/',
    liveButtonText: 'Try Live',
    githubUrl: 'https://github.com/JuanchoGithub/png-url-to-svg',
  },
  {
    title: '3ro Lectura',
    description: 'Interactive reading tool for third graders, with updated timelines and stories.',
    language: 'TypeScript',
    liveUrl: 'https://3rolectura.vercel.app/',
    liveButtonText: 'Explore Live',
    githubUrl: 'https://github.com/JuanchoGithub/3rolectura',
  },
  {
    title: 'MateChicos',
    description: 'Fun math exercises and games designed for children to learn through play.',
    language: 'TypeScript',
    liveUrl: 'https://matechicos.vercel.app/',
    liveButtonText: 'Play Live',
    githubUrl: 'https://github.com/JuanchoGithub/matechicos',
  },
];
