import { Project, ProjectCategoryKey } from './types';

export const projectCategories: ProjectCategoryKey[] = [
  'games-entertainment',
  'tools-utilities',
  'educational-apps',
  'creative-experimental',
];

export const projects: Project[] = [
  {
    title: { 
      en: 'Mini Coder', 
      es: 'Mini Coder',
      pt: 'Mini Coder',
      it: 'Mini Coder',
      ja: 'ミニコーダー',
      zh: '迷你编码器',
    },
    description: { 
      en: 'A compact online code editor for quick experiments and sharing snippets, with PWA support for offline access.',
      es: 'Un editor de código en línea compacto para experimentos rápidos y compartir fragmentos, con soporte PWA para acceso sin conexión.',
      pt: 'Um editor de código online compacto para experimentos rápidos e compartilhamento de trechos, com suporte PWA para acesso offline.',
      it: 'Un editor di codice online compatto per esperimenti veloci e la condivisione di snippet, con supporto PWA per l\'accesso offline.',
      ja: 'オフラインアクセス用のPWAをサポートした、簡単な実験やスニペットの共有に便利なコンパクトなオンラインコードエディタ。',
      zh: '一个紧凑的在线代码编辑器，用于快速实验和共享代码片段，支持PWA离线访问。',
    },
    language: 'TypeScript',
    liveUrl: 'https://mini-coder.vercel.app',
    liveButtonText: { 
      en: 'Code Live', 
      es: 'Codear en Vivo',
      pt: 'Codificar ao Vivo',
      it: 'Codice Live',
      ja: 'ライブでコーディング',
      zh: '在线编码',
    },
    githubUrl: 'https://github.com/JuanchoGithub/mini-coder',
    category: 'tools-utilities',
  },
  {
    title: { 
      en: 'Gym Tracker', 
      es: 'Gym Tracker',
      pt: 'Gym Tracker',
      it: 'Gym Tracker',
      ja: 'ジムトラッカー',
      zh: '健身追踪器',
    },
    description: {
      en: 'A web app to track gym workouts and progress, featuring improved initial set population for a smoother experience.',
      es: 'Una aplicación web para seguir los entrenamientos del gimnasio y el progreso, con una población inicial de series mejorada para una experiencia más fluida.',
      pt: 'Um aplicativo da web para acompanhar treinos e progresso na academia, com preenchimento inicial de séries aprimorado para uma experiência mais suave.',
      it: 'Un\'app web per monitorare gli allenamenti e i progressi in palestra, con un migliorato popolamento iniziale delle serie per un\'esperienza più fluida.',
      ja: 'よりスムーズな体験のために初期セット入力を改善した、ジムのワークアウトと進捗を追跡するウェブアプリ。',
      zh: '一个用于追踪健身房锻炼和进度的网络应用，具有改进的初始组数填充功能，以获得更流畅的体验。',
    },
    language: 'TypeScript',
    liveUrl: 'https://gym-tracker-rho-three.vercel.app',
    liveButtonText: { 
      en: 'Track Live', 
      es: 'Seguir en Vivo',
      pt: 'Acompanhar ao Vivo',
      it: 'Traccia Live',
      ja: 'ライブで追跡',
      zh: '实时追踪',
    },
    githubUrl: 'https://github.com/JuanchoGithub/gym-tracker',
    category: 'tools-utilities',
  },
  {
    title: { 
      en: 'Truco AI', 
      es: 'Truco AI',
      pt: 'Truco AI',
      it: 'Truco AI',
      ja: 'トルコAI',
      zh: 'Truco AI',
    },
    description: {
      en: 'AI-powered single-player Truco card game with bluffing and unpredictability. Classic Argentine game!',
      es: 'Juego de cartas Truco para un solo jugador impulsado por IA con faroles e imprevisibilidad. ¡Un clásico juego argentino!',
      pt: 'Jogo de cartas Truco para um jogador com IA, com blefes e imprevisibilidade. Jogo argentino clássico!',
      it: 'Gioco di carte Truco per giocatore singolo potenziato dall\'IA con bluff e imprevedibilità. Un classico gioco argentino!',
      ja: 'ブラフと予測不可能性を備えたAI搭載のシングルプレイヤートルコカードゲーム。アルゼンチンの古典的なゲームです！',
      zh: '由AI驱动的单人Truco纸牌游戏，具有虚张声势和不可预测性。经典的阿根廷游戏！',
    },
    language: 'TypeScript',
    liveUrl: 'https://trucai.vercel.app',
    liveButtonText: { 
      en: 'Play Live', 
      es: 'Jugar en Vivo',
      pt: 'Jogar ao Vivo',
      it: 'Gioca Live',
      ja: 'ライブでプレイ',
      zh: '在线玩',
    },
    githubUrl: 'https://github.com/JuanchoGithub/truco-ai',
    category: 'games-entertainment',
  },
  {
    title: { 
      en: 'Starfleet Ship Creator', 
      es: 'Creador de Naves Starfleet',
      pt: 'Criador de Naves da Frota Estelar',
      it: 'Creatore di Navi della Flotta Stellare',
      ja: 'スターフリート艦船クリエーター',
      zh: '星际舰队飞船创造者',
    },
    description: {
      en: 'A creative tool for designing and visualizing custom Starfleet ships with adjustable nacelle grill colors and intensity.',
      es: 'Una herramienta creativa para diseñar y visualizar naves personalizadas de Starfleet con colores e intensidad de parrilla de nacelle ajustables.',
      pt: 'Uma ferramenta criativa para projetar e visualizar naves personalizadas da Frota Estelar com cores e intensidade da grade da nacele ajustáveis.',
      it: 'Uno strumento creativo per progettare e visualizzare navi personalizzate della Flotta Stellare con colori e intensità della griglia della navicella regolabili.',
      ja: 'ナセルグリルの色と強度を調整して、カスタムのスターフリート艦船を設計および視覚化するためのクリエイティブなツール。',
      zh: '一个用于设计和可视化自定义星际舰队飞船的创意工具，具有可调节的曲速舱格栅颜色和强度。',
    },
    language: 'TypeScript',
    liveUrl: 'https://starfleet-ship-creator.vercel.app',
    liveButtonText: { 
      en: 'Design Live', 
      es: 'Diseñar en Vivo',
      pt: 'Projetar ao Vivo',
      it: 'Progetta Live',
      ja: 'ライブでデザイン',
      zh: '在线设计',
    },
    githubUrl: 'https://github.com/JuanchoGithub/starfleet-ship-creator',
    category: 'creative-experimental',
  },
  {
    title: { 
      en: 'MateChicos v2', 
      es: 'MateChicos v2',
      pt: 'MateChicos v2',
      it: 'MateChicos v2',
      ja: 'マテチコス v2',
      zh: '数学小子 v2',
    },
    description: {
      en: 'The next version of MateChicos, featuring an improved NumberPad for better interaction in fun math games for kids.',
      es: 'La próxima versión de MateChicos, con un NumberPad mejorado para una mejor interacción en divertidos juegos de matemáticas para niños.',
      pt: 'A próxima versão do MateChicos, com um NumberPad aprimorado para melhor interação em divertidos jogos de matemática para crianças.',
      it: 'La prossima versione di MateChicos, con un NumberPad migliorato per una migliore interazione nei divertenti giochi di matematica per bambini.',
      ja: '子供向けの楽しい算数ゲームでより良いインタラクションを実現する、改良されたナンバーパッドを搭載したマテチコスの次期バージョン。',
      zh: 'MateChicos 的下一个版本，为孩子们有趣的数学游戏提供了改进的数字键盘，以实现更好的互动。',
    },
    language: 'TypeScript',
    liveUrl: 'https://matechicos-v2.vercel.app',
    liveButtonText: { 
      en: 'Play Live', 
      es: 'Jugar en Vivo',
      pt: 'Jogar ao Vivo',
      it: 'Gioca Live',
      ja: 'ライブでプレイ',
      zh: '在线玩',
    },
    githubUrl: 'https://github.com/JuanchoGithub/matechicos-v2',
    category: 'educational-apps',
  },
  {
    title: { 
      en: 'Starfleet Battles 3D', 
      es: 'Batallas Starfleet 3D',
      pt: 'Batalhas da Frota Estelar 3D',
      it: 'Battaglie della Flotta Stellare 3D',
      ja: 'スターフリートバトル3D',
      zh: '星际舰队战役3D',
    },
    description: {
      en: 'A 3D browser-based game simulating starship combat in the Star Trek universe, built with Vite.',
      es: 'Un juego 3D para navegador que simula combates de naves estelares en el universo de Star Trek, construido con Vite.',
      pt: 'Um jogo 3D para navegador que simula combate de naves estelares no universo de Star Trek, construído com Vite.',
      it: 'Un gioco 3D basato su browser che simula il combattimento tra astronavi nell\'universo di Star Trek, costruito con Vite.',
      ja: 'Viteで構築された、スタートレックの世界での宇宙船戦闘をシミュレートする3Dブラウザベースのゲーム。',
      zh: '一款基于浏览器的3D游戏，模拟星际迷航宇宙中的星舰战斗，使用Vite构建。',
    },
    language: 'TypeScript',
    liveUrl: 'https://starfleet-battles-3d.vercel.app',
    liveButtonText: { 
      en: 'Battle Live', 
      es: 'Luchar en Vivo',
      pt: 'Batalhar ao Vivo',
      it: 'Combatti Live',
      ja: 'ライブでバトル',
      zh: '在线战斗',
    },
    githubUrl: 'https://github.com/JuanchoGithub/starfleet-battles-3d',
    category: 'games-entertainment',
  },
  {
    title: { 
      en: '3ro Lectura', 
      es: '3ro Lectura',
      pt: 'Leitura para 3ª Série',
      it: 'Lettura per la Terza Elementare',
      ja: '3年生の読書',
      zh: '三年级阅读',
    },
    description: {
      en: 'Interactive reading tool for third graders, featuring engaging stories and updated timelines to aid learning.',
      es: 'Herramienta de lectura interactiva para alumnos de tercer grado, con historias atractivas y líneas de tiempo actualizadas para facilitar el aprendizaje.',
      pt: 'Ferramenta de leitura interativa para alunos da terceira série, com histórias envolventes e cronogramas atualizados para auxiliar no aprendizado.',
      it: 'Strumento di lettura interattivo per alunni di terza elementare, con storie coinvolgenti e linee temporali aggiornate per facilitare l\'apprendimento.',
      ja: '魅力的な物語と学習を助けるための更新されたタイムラインを備えた、3年生向けのインタラクティブな読書ツール。',
      zh: '为三年级学生设计的互动阅读工具，提供引人入胜的故事和更新的时间线以帮助学习。',
    },
    language: 'TypeScript',
    liveUrl: 'https://3rolectura.vercel.app',
    liveButtonText: { 
      en: 'Explore Live', 
      es: 'Explorar en Vivo',
      pt: 'Explorar ao Vivo',
      it: 'Esplora Live',
      ja: 'ライブで探る',
      zh: '在线探索',
    },
    githubUrl: 'https://github.com/JuanchoGithub/3rolectura',
    category: 'educational-apps',
  },
  {
    title: { 
      en: 'Lecturalia', 
      es: 'Lecturalia',
      pt: 'Lecturalia',
      it: 'Lecturalia',
      ja: 'レクチュラリア',
      zh: '阅读乐',
    },
    description: {
      en: 'Interactive PWA reading app for kids in 3rd grade and up, with engaging stories and questions.',
      es: 'Aplicación de lectura PWA interactiva para niños de 3er grado en adelante, con historias y preguntas atractivas.',
      pt: 'Aplicativo de leitura PWA interativo para crianças da 3ª série em diante, com histórias e perguntas envolventes.',
      it: 'App di lettura PWA interattiva per bambini dalla terza elementare in su, con storie e domande coinvolgenti.',
      ja: '魅力的な物語と質問を備えた、3年生以上の子供向けのインタラクティブなPWA読書アプリ。',
      zh: '为三年级及以上儿童设计的互动PWA阅读应用，提供引人入胜的故事和问题。',
    },
    language: 'TypeScript',
    liveUrl: 'https://lecturalia.vercel.app',
    liveButtonText: { 
      en: 'Explore Live', 
      es: 'Explorar en Vivo',
      pt: 'Explorar ao Vivo',
      it: 'Esplora Live',
      ja: 'ライブで探る',
      zh: '在线探索',
    },
    githubUrl: 'https://github.com/JuanchoGithub/lecturalia',
    category: 'educational-apps',
  },
  {
    title: { 
      en: 'Super Vibe Trek', 
      es: 'Super Vibe Trek',
      pt: 'Super Vibe Trek',
      it: 'Super Vibe Trek',
      ja: 'スーパーバイブトレック',
      zh: '超级星途',
    },
    description: {
      en: 'Browser-based turn-based Star Trek game: explore the galaxy on a hex grid, manage crew, and handle diplomacy/combat.',
      es: 'Juego de Star Trek por turnos para navegador: explora la galaxia en una cuadrícula hexagonal, gestiona la tripulación y maneja la diplomacia/combate.',
      pt: 'Jogo de Star Trek por turnos para navegador: explore a galáxia em uma grade hexagonal, gerencie a tripulação e lide com diplomacia/combate.',
      it: 'Gioco di Star Trek a turni basato su browser: esplora la galassia su una griglia esagonale, gestisci l\'equipaggio e affronta diplomazia/combattimento.',
      ja: 'ブラウザベースのターン制スタートレックゲーム：ヘックスグリッドで銀河を探索し、乗組員を管理し、外交/戦闘を処理します。',
      zh: '基于浏览器的回合制星际迷航游戏：在六边形网格上探索银河系，管理船员，并处理外交/战斗。',
    },
    language: 'TypeScript',
    liveUrl: 'https://super-vibe-trek.vercel.app',
    liveButtonText: { 
      en: 'Explore Live', 
      es: 'Explorar en Vivo',
      pt: 'Explorar ao Vivo',
      it: 'Esplora Live',
      ja: 'ライブで探る',
      zh: '在线探索',
    },
    githubUrl: 'https://github.com/JuanchoGithub/Star-Trek-Exploration',
    category: 'games-entertainment',
  },
  {
    title: { 
      en: 'Solitaire Collection', 
      es: 'Colección de Solitarios',
      pt: 'Coleção de Paciência',
      it: 'Collezione di Solitari',
      ja: 'ソリティアコレクション',
      zh: '纸牌合集',
    },
    description: {
      en: 'A PWA collection of classic solitaire games with smooth animations and a clean, responsive design.',
      es: 'Una colección PWA de juegos de solitario clásicos con animaciones fluidas y un diseño limpio y responsivo.',
      pt: 'Uma coleção PWA de jogos de paciência clássicos com animações suaves e um design limpo e responsivo.',
      it: 'Una collezione PWA di classici giochi di solitario con animazioni fluide e un design pulito e reattivo.',
      ja: 'スムーズなアニメーションとクリーンでレスポンシブなデザインを備えた、クラシックなソリティアゲームのPWAコレクション。',
      zh: '一个PWA经典纸牌游戏合集，具有流畅的动画和简洁、响应式的设计。',
    },
    language: 'TypeScript',
    liveUrl: 'https://lonely-cards.vercel.app',
    liveButtonText: { 
      en: 'Play Live', 
      es: 'Jugar en Vivo',
      pt: 'Jogar ao Vivo',
      it: 'Gioca Live',
      ja: 'ライブでプレイ',
      zh: '在线玩',
    },
    githubUrl: 'https://github.com/JuanchoGithub/solitaire-collection',
    category: 'games-entertainment',
  },
  {
    title: { 
      en: '3D Procedural FPS', 
      es: 'FPS Procedural 3D',
      pt: 'FPS Procedural 3D',
      it: 'FPS Procedurale 3D',
      ja: '3DプロシージャルFPS',
      zh: '3D程序化第一人称射击游戏',
    },
    description: {
      en: 'A 3D first-person shooter with procedurally generated levels, focusing on fast-paced game flow and replayability.',
      es: 'Un shooter en primera persona 3D con niveles generados proceduralmente, centrado en un flujo de juego rápido y rejugabilidad.',
      pt: 'Um jogo de tiro em primeira pessoa 3D com níveis gerados proceduralmente, focado em um fluxo de jogo rápido e rejogabilidade.',
      it: 'Uno sparatutto in prima persona 3D con livelli generati proceduralmente, incentrato su un flusso di gioco frenetico e rigiocabilità.',
      ja: 'プロシージャルに生成されたレベルを持つ3Dファーストパーソンシューターで、ペースの速いゲームフローとリプレイ性に焦点を当てています。',
      zh: '一款具有程序生成关卡的3D第一人称射击游戏，专注于快节奏的游戏流程和可玩性。',
    },
    language: 'TypeScript',
    liveUrl: 'https://3d-fps.vercel.app',
    liveButtonText: { 
      en: 'Play Live', 
      es: 'Jugar en Vivo',
      pt: 'Jogar ao Vivo',
      it: 'Gioca Live',
      ja: 'ライブでプレイ',
      zh: '在线玩',
    },
    githubUrl: 'https://github.com/JuanchoGithub/3D-Proc-FPS',
    category: 'games-entertainment',
  },
  {
    title: { 
      en: 'Mermaid Online', 
      es: 'Mermaid Online',
      pt: 'Mermaid Online',
      it: 'Mermaid Online',
      ja: 'マーメイドオンライン',
      zh: 'Mermaid 在线工具',
    },
    description: {
      en: 'Online visual builder for Mermaid diagrams with pan, zoom, and "Fit to Screen" functionality to create flowcharts effortlessly.',
      es: 'Constructor visual en línea para diagramas Mermaid con funciones de paneo, zoom y "Ajustar a la pantalla" para crear diagramas de flujo sin esfuerzo.',
      pt: 'Construtor visual online para diagramas Mermaid com funcionalidades de panorâmica, zoom e "Ajustar à Tela" para criar fluxogramas sem esforço.',
      it: 'Costruttore visivo online per diagrammi Mermaid con funzionalità di pan, zoom e "Adatta allo schermo" per creare diagrammi di flusso senza sforzo.',
      ja: 'パン、ズーム、および「画面に合わせる」機能を備えたマーメイド図のオンラインビジュアルビルダーで、フローチャートを簡単に作成できます。',
      zh: '用于Mermaid图表的在线可视化构建器，具有平移、缩放和“适应屏幕”功能，可轻松创建流程图。',
    },
    language: 'TypeScript',
    liveUrl: 'https://mermaid-online.vercel.app',
    liveButtonText: { 
      en: 'Build Live', 
      es: 'Construir en Vivo',
      pt: 'Construir ao Vivo',
      it: 'Costruisci Live',
      ja: 'ライブで構築',
      zh: '在线构建',
    },
    githubUrl: 'https://github.com/JuanchoGithub/online-diagram',
    category: 'tools-utilities',
  },
  {
    title: { 
      en: 'Homepage Portfolio', 
      es: 'Portfolio Personal',
      pt: 'Portfólio Pessoal',
      it: 'Portfolio Personale',
      ja: 'ホームページポートフォリオ',
      zh: '个人作品集',
    },
    description: {
      en: 'This very portfolio website, built with React and Tailwind CSS to showcase my personal projects.',
      es: 'Este mismo sitio de portfolio, construido con React y Tailwind CSS para mostrar mis proyectos personales.',
      pt: 'Este mesmo site de portfólio, construído com React e Tailwind CSS para mostrar meus projetos pessoais.',
      it: 'Questo stesso sito portfolio, costruito con React e Tailwind CSS per presentare i miei progetti personali.',
      ja: 'このポートフォリオサイト自体も、ReactとTailwind CSSで構築されており、私の個人的なプロジェクトを紹介しています。',
      zh: '就是这个作品集网站，使用 React 和 Tailwind CSS 构建，用于展示我的个人项目。',
    },
    language: 'TypeScript',
    liveUrl: 'https://jay-jay.vercel.app',
    liveButtonText: { 
      en: 'View Source', 
      es: 'Ver Código',
      pt: 'Ver Código Fonte',
      it: 'Vedi Sorgente',
      ja: 'ソースを表示',
      zh: '查看源代码',
    },
    githubUrl: 'https://github.com/JuanchoGithub/homepage',
    category: 'tools-utilities',
  },
  {
    title: { 
      en: 'Head Tracking 3D Test', 
      es: 'Test de Seguimiento de Cabeza 3D',
      pt: 'Teste de Rastreamento de Cabeça 3D',
      it: 'Test di Tracciamento della Testa 3D',
      ja: 'ヘッドトラッキング3Dテスト',
      zh: '头部追踪3D测试',
    },
    description: {
      en: 'Experimental 3D head tracking demo using a webcam, with infinity mirror effects and grid visuals.',
      es: 'Demo experimental de seguimiento de cabeza en 3D usando una webcam, con efectos de espejo infinito y visuales de cuadrícula.',
      pt: 'Demonstração experimental de rastreamento de cabeça 3D usando uma webcam, com efeitos de espelho infinito e visuais de grade.',
      it: 'Demo sperimentale di tracciamento della testa 3D tramite webcam, con effetti di specchio infinito e visualizzazioni a griglia.',
      ja: 'ウェブカメラを使用した実験的な3Dヘッドトラッキングデモで、無限ミラー効果とグリッドビジュアルを備えています。',
      zh: '使用网络摄像头的实验性3D头部追踪演示，具有无限镜像效果和网格视觉效果。',
    },
    language: 'TypeScript',
    liveUrl: 'https://head-tracking-3d-test.vercel.app',
    liveButtonText: { 
      en: 'View Live', 
      es: 'Ver en Vivo',
      pt: 'Ver ao Vivo',
      it: 'Vedi Live',
      ja: 'ライブで表示',
      zh: '在线查看',
    },
    githubUrl: 'https://github.com/JuanchoGithub/head-tracking-3d-test',
    category: 'creative-experimental',
  },
  {
    title: { 
      en: 'Kirby Jump', 
      es: 'Kirby Jump',
      pt: 'Kirby Jump',
      it: 'Kirby Jump',
      ja: 'カービージャンプ',
      zh: '卡比跳跃',
    },
    description: {
      en: 'A vibe-coded Kirby obstacle course inspired by Roblox, with level difficulty signs—a fun project built with my son!',
      es: 'Un juego de obstáculos de Kirby programado "con onda" e inspirado en Roblox, con señales de dificultad de nivel. ¡Un proyecto divertido hecho con mi hijo!',
      pt: 'Um percurso de obstáculos do Kirby com código "vibe" inspirado no Roblox, com sinais de dificuldade de nível—um projeto divertido construído com meu filho!',
      it: 'Un percorso a ostacoli di Kirby codificato "con vibe" e ispirato a Roblox, con segnali di difficoltà di livello—un progetto divertente costruito con mio figlio!',
      ja: 'Robloxにインスパイアされた、レベル難易度サイン付きの「バイブコード」カービィ障害物コース—息子と一緒に作った楽しいプロジェクトです！',
      zh: '一个受Roblox启发的、充满活力的卡比障碍课程，带有等级难度标志——一个和我儿子一起做的有趣项目！',
    },
    language: 'TypeScript',
    liveUrl: 'https://kirby-jump-nine.vercel.app',
    liveButtonText: { 
      en: 'Play Live', 
      es: 'Jugar en Vivo',
      pt: 'Jogar ao Vivo',
      it: 'Gioca Live',
      ja: 'ライブでプレイ',
      zh: '在线玩',
    },
    githubUrl: 'https://github.com/JuanchoGithub/Kirby-Jump-',
    category: 'games-entertainment',
  },
  {
    title: { 
      en: 'PNG URL to SVG', 
      es: 'PNG URL a SVG',
      pt: 'URL de PNG para SVG',
      it: 'Da URL PNG a SVG',
      ja: 'PNG URLからSVGへ',
      zh: 'PNG网址转SVG',
    },
    description: {
      en: 'Simple tool to convert PNG images from URLs to SVGs, now featuring background removal.',
      es: 'Herramienta simple para convertir imágenes PNG desde URLs a SVG, ahora con eliminación de fondo.',
      pt: 'Ferramenta simples para converter imagens PNG de URLs para SVGs, agora com remoção de fundo.',
      it: 'Semplice strumento per convertire immagini PNG da URL a SVG, ora con rimozione dello sfondo.',
      ja: 'URLからPNG画像をSVGに変換するシンプルなツールで、背景除去機能も搭載しています。',
      zh: '一个简单的工具，可将URL中的PNG图像转换为SVG，现在具有背景去除功能。',
    },
    language: 'TypeScript',
    liveUrl: 'https://png-url-to-svg.vercel.app',
    liveButtonText: { 
      en: 'Try Live', 
      es: 'Probar en Vivo',
      pt: 'Testar ao Vivo',
      it: 'Prova Live',
      ja: 'ライブで試す',
      zh: '在线尝试',
    },
    githubUrl: 'https://github.com/JuanchoGithub/png-url-to-svg',
    category: 'tools-utilities',
  },
  {
    title: { 
      en: 'MateChicos', 
      es: 'MateChicos',
      pt: 'MateChicos',
      it: 'MateChicos',
      ja: 'マテチコス',
      zh: '数学小子',
    },
    description: {
      en: 'Fun math exercises and games designed for children to learn through play and interaction.',
      es: 'Ejercicios y juegos de matemáticas divertidos diseñados para que los niños aprendan a través del juego y la interacción.',
      pt: 'Exercícios e jogos divertidos de matemática projetados para crianças aprenderem através da brincadeira e interação.',
      it: 'Esercizi e giochi matematici divertenti progettati per i bambini per imparare attraverso il gioco e l\'interazione.',
      ja: '子供たちが遊びと対話を通じて学ぶために設計された楽しい算数の練習問題とゲーム。',
      zh: '为儿童设计的有趣数学练习和游戏，让他们通过玩耍和互动来学习。',
    },
    language: 'TypeScript',
    liveUrl: 'https://matechicos.vercel.app',
    liveButtonText: { 
      en: 'Play Live', 
      es: 'Jugar en Vivo',
      pt: 'Jogar ao Vivo',
      it: 'Gioca Live',
      ja: 'ライブでプレイ',
      zh: '在线玩',
    },
    githubUrl: 'https://github.com/JuanchoGithub/matechicos',
    category: 'educational-apps',
  },
];