import { Project } from './types';

export const projects: Project[] = [
  {
    title: 'Mini Coder',
    description: 'A compact online code editor for quick experiments and sharing snippets, with PWA support for offline access.',
    language: 'TypeScript',
    liveUrl: 'https://mini-coder.vercel.app',
    liveButtonText: 'Code Live',
    githubUrl: 'https://github.com/JuanchoGithub/mini-coder',
  },
  {
    title: 'Gym Tracker',
    description: 'A web app to track gym workouts and progress, featuring improved initial set population for a smoother experience.',
    language: 'TypeScript',
    liveUrl: 'https://gym-tracker-rho-three.vercel.app',
    liveButtonText: 'Track Live',
    githubUrl: 'https://github.com/JuanchoGithub/gym-tracker',
  },
  {
    title: 'Truco AI',
    description: 'AI-powered single-player Truco card game with bluffing and unpredictability. Classic Argentine game!',
    language: 'TypeScript',
    liveUrl: 'https://trucai.vercel.app',
    liveButtonText: 'Play Live',
    githubUrl: 'https://github.com/JuanchoGithub/truco-ai',
  },
  {
    title: 'Starfleet Ship Creator',
    description: 'A creative tool for designing and visualizing custom Starfleet ships with adjustable nacelle grill colors and intensity.',
    language: 'TypeScript',
    liveUrl: 'https://starfleet-ship-creator.vercel.app',
    liveButtonText: 'Design Live',
    githubUrl: 'https://github.com/JuanchoGithub/starfleet-ship-creator',
  },
  {
    title: 'MateChicos v2',
    description: 'The next version of MateChicos, featuring an improved NumberPad for better interaction in fun math games for kids.',
    language: 'TypeScript',
    liveUrl: 'https://matechicos-v2.vercel.app',
    liveButtonText: 'Play Live',
    githubUrl: 'https://github.com/JuanchoGithub/matechicos-v2',
  },
  {
    title: 'Starfleet Battles 3D',
    description: 'A 3D browser-based game simulating starship combat in the Star Trek universe, built with Vite.',
    language: 'TypeScript',
    liveUrl: 'https://starfleet-battles-3d.vercel.app',
    liveButtonText: 'Battle Live',
    githubUrl: 'https://github.com/JuanchoGithub/starfleet-battles-3d',
  },
  {
    title: '3ro Lectura',
    description: 'Interactive reading tool for third graders, featuring engaging stories and updated timelines to aid learning.',
    language: 'TypeScript',
    liveUrl: 'https://3rolectura.vercel.app',
    liveButtonText: 'Explore Live',
    githubUrl: 'https://github.com/JuanchoGithub/3rolectura',
  },
  {
    title: 'Lecturalia',
    description: 'Interactive PWA reading app for kids in 3rd grade and up, with engaging stories and questions.',
    language: 'TypeScript',
    liveUrl: 'https://lecturalia.vercel.app',
    liveButtonText: 'Explore Live',
    githubUrl: 'https://github.com/JuanchoGithub/lecturalia',
  },
  {
    title: 'Super Vibe Trek',
    description: 'Browser-based turn-based Star Trek game: explore the galaxy on a hex grid, manage crew, and handle diplomacy/combat.',
    language: 'TypeScript',
    liveUrl: 'https://super-vibe-trek.vercel.app',
    liveButtonText: 'Explore Live',
    githubUrl: 'https://github.com/JuanchoGithub/Star-Trek-Exploration',
  },
  {
    title: 'Solitaire Collection',
    description: 'A PWA collection of classic solitaire games with smooth animations and a clean, responsive design.',
    language: 'TypeScript',
    liveUrl: 'https://lonely-cards.vercel.app',
    liveButtonText: 'Play Live',
    githubUrl: 'https://github.com/JuanchoGithub/solitaire-collection',
  },
  {
    title: '3D Procedural FPS',
    description: 'A 3D first-person shooter with procedurally generated levels, focusing on fast-paced game flow and replayability.',
    language: 'TypeScript',
    liveUrl: 'https://3d-fps.vercel.app',
    liveButtonText: 'Play Live',
    githubUrl: 'https://github.com/JuanchoGithub/3D-Proc-FPS',
  },
  {
    title: 'Mermaid Online',
    description: 'Online visual builder for Mermaid diagrams with pan, zoom, and "Fit to Screen" functionality to create flowcharts effortlessly.',
    language: 'TypeScript',
    liveUrl: 'https://mermaid-online.vercel.app',
    liveButtonText: 'Build Live',
    githubUrl: 'https://github.com/JuanchoGithub/online-diagram',
  },
  {
    title: 'Homepage Portfolio',
    description: 'This very portfolio website, built with React and Tailwind CSS to showcase my personal projects.',
    language: 'TypeScript',
    liveUrl: 'https://jay-jay.vercel.app',
    liveButtonText: 'View Source',
    githubUrl: 'https://github.com/JuanchoGithub/homepage',
  },
  {
    title: 'Head Tracking 3D Test',
    description: 'Experimental 3D head tracking demo using a webcam, with infinity mirror effects and grid visuals.',
    language: 'TypeScript',
    liveUrl: 'https://head-tracking-3d-test.vercel.app',
    liveButtonText: 'View Live',
    githubUrl: 'https://github.com/JuanchoGithub/head-tracking-3d-test',
  },
  {
    title: 'Kirby Jump',
    description: 'A vibe-coded Kirby obstacle course inspired by Roblox, with level difficulty signs—a fun project built with my son!',
    language: 'TypeScript',
    liveUrl: 'https://kirby-jump-nine.vercel.app',
    liveButtonText: 'Play Live',
    githubUrl: 'https://github.com/JuanchoGithub/Kirby-Jump-',
  },
  {
    title: 'PNG URL to SVG',
    description: 'Simple tool to convert PNG images from URLs to SVGs, now featuring background removal.',
    language: 'TypeScript',
    liveUrl: 'https://png-url-to-svg.vercel.app',
    liveButtonText: 'Try Live',
    githubUrl: 'https://github.com/JuanchoGithub/png-url-to-svg',
  },
  {
    title: 'MateChicos',
    description: 'Fun math exercises and games designed for children to learn through play and interaction.',
    language: 'TypeScript',
    liveUrl: 'https://matechicos.vercel.app',
    liveButtonText: 'Play Live',
    githubUrl: 'https://github.com/JuanchoGithub/matechicos',
  },
];
